"""
3-DOF arm: SymPy dynamics derivation + C++ header export.
Usage:
    python derive_and_export.py --output ../generated/dynamics_generated.hpp
"""
import argparse
import os
import sys
import sympy as sp


def derive_dynamics():
    """Return (M_mat, Cqdq, g_vec) as sympy matrices in independent symbols."""
    print("[derive] Setting up symbols...", flush=True)
    t = sp.symbols('t')
    q1f, q2f, q3f = [sp.Function(f'q{i}')(t) for i in range(1, 4)]
    dq1, dq2, dq3 = [sp.diff(q, t) for q in [q1f, q2f, q3f]]
    ddq1, ddq2, ddq3 = [sp.diff(dq, t) for dq in [dq1, dq2, dq3]]

    L2s, L3s = sp.symbols('L2 L3', positive=True)
    m2s, m3s = sp.symbols('m2 m3', positive=True)
    gs       = sp.symbols('g', positive=True)

    def Rz(a):
        return sp.Matrix([[sp.cos(a), -sp.sin(a), 0],
                          [sp.sin(a),  sp.cos(a), 0],
                          [0, 0, 1]])

    def Ry(a):
        return sp.Matrix([[ sp.cos(a), 0, sp.sin(a)],
                          [0, 1, 0],
                          [-sp.sin(a), 0, sp.cos(a)]])

    e_x   = sp.Matrix([1, 0, 0])
    R12   = Rz(q1f) * Ry(q2f)
    R123  = Rz(q1f) * Ry(q2f + q3f)
    p_c2  = R12  * (sp.Rational(1, 2) * L2s * e_x)
    p_c3  = R12  * (L2s * e_x) + R123 * (sp.Rational(1, 2) * L3s * e_x)
    v_c2  = sp.diff(p_c2, t)
    v_c3  = sp.diff(p_c3, t)

    y_rot   = Rz(q1f) * sp.Matrix([0, 1, 0])
    z_world = sp.Matrix([0, 0, 1])
    omega2  = dq1 * z_world + dq2 * y_rot
    omega3  = omega2 + dq3 * y_rot
    axis2   = R12  * e_x
    axis3   = R123 * e_x

    def rot_ke(m, L, omega, axis):
        om2   = (omega.T * omega)[0, 0]
        along = (omega.T * axis)[0, 0]
        return sp.Rational(1, 24) * m * L**2 * (om2 - along**2)

    print("[derive] Building Lagrangian...", flush=True)
    T = (sp.Rational(1, 2) * m2s * (v_c2.T * v_c2)[0, 0] + rot_ke(m2s, L2s, omega2, axis2) +
         sp.Rational(1, 2) * m3s * (v_c3.T * v_c3)[0, 0] + rot_ke(m3s, L3s, omega3, axis3))
    T = sp.expand(T)
    U   = m2s * gs * p_c2[2] + m3s * gs * p_c3[2]
    Lag = T - U

    qs   = [q1f, q2f, q3f]
    dqs  = [dq1, dq2, dq3]
    ddqs = [ddq1, ddq2, ddq3]

    print("[derive] Computing Euler-Lagrange equations (may take 1-3 min)...", flush=True)
    EOM = []
    for i, (qi, dqi) in enumerate(zip(qs, dqs)):
        print(f"  EOM[{i+1}]...", flush=True)
        raw = sp.diff(sp.diff(Lag, dqi), t) - sp.diff(Lag, qi)
        EOM.append(sp.trigsimp(raw))

    Q   = sp.symbols('Q1 Q2 Q3')
    DQ  = sp.symbols('DQ1 DQ2 DQ3')
    DDQ = sp.symbols('DDQ1 DDQ2 DDQ3')

    def to_indep(expr):
        e = expr
        for ddqi, sym in zip(ddqs, DDQ): e = e.subs(ddqi, sym)
        for dqi,  sym in zip(dqs,  DQ):  e = e.subs(dqi,  sym)
        for qi,   sym in zip(qs,   Q):   e = e.subs(qi,   sym)
        return e

    EOM_i = [to_indep(e) for e in EOM]

    print("[derive] Extracting M, C, g...", flush=True)
    M_mat = sp.zeros(3, 3)
    for i in range(3):
        for j in range(3):
            M_mat[i, j] = sp.trigsimp(sp.diff(EOM_i[i], DDQ[j]))

    zero_ddq = {DDQ[k]: 0 for k in range(3)}
    rest  = sp.Matrix([sp.trigsimp(EOM_i[i].subs(zero_ddq)) for i in range(3)])
    g_vec = sp.trigsimp(rest.subs({DQ[k]: 0 for k in range(3)}))
    Cqdq  = sp.trigsimp(rest - g_vec)

    return M_mat, Cqdq, g_vec, Q, DQ, L2s, L3s, m2s, m3s, gs


def generate_header(M_mat, Cqdq, g_vec, Q, DQ, L2s, L3s, m2s, m3s, gs, out_path):
    q1_, q2_, q3_       = sp.symbols('q1 q2 q3')
    dq1_, dq2_, dq3_    = sp.symbols('dq1 dq2 dq3')
    L2_, L3_, m2_, m3_, grav_ = sp.symbols('L2 L3 m2 m3 grav')

    subs = {Q[0]: q1_, Q[1]: q2_, Q[2]: q3_,
            DQ[0]: dq1_, DQ[1]: dq2_, DQ[2]: dq3_,
            L2s: L2_, L3s: L3_, m2s: m2_, m3s: m3_, gs: grav_}

    all_exprs = ([M_mat[i, j].subs(subs) for i in range(3) for j in range(3)] +
                 [Cqdq[i].subs(subs) for i in range(3)] +
                 [g_vec[i].subs(subs) for i in range(3)])

    print("[generate] Running CSE...", flush=True)
    repl, reduced = sp.cse(all_exprs, symbols=sp.numbered_symbols('tmp'))

    lines = [
        "#pragma once",
        "// AUTO-GENERATED by python/derive_and_export.py — do not edit",
        "#include <cmath>",
        "#include <Eigen/Dense>",
        "",
        "namespace robot_generated {",
        "",
        "struct DynTerms {",
        "    Eigen::Matrix3d M;",
        "    Eigen::Vector3d Cdq;  // C(q,dq)*dq",
        "    Eigen::Vector3d gv;   // gravity vector",
        "};",
        "",
        "inline DynTerms compute_dynamics(",
        "    double q1, double q2, double q3,",
        "    double dq1, double dq2, double dq3,",
        "    double L2, double L3, double m2, double m3, double grav)",
        "{",
    ]

    for sym, expr in repl:
        lines.append(f"    const double {sym} = {sp.ccode(expr)};")

    lines.append("    DynTerms d{};")

    idx = 0
    for i in range(3):
        for j in range(3):
            lines.append(f"    d.M({i},{j}) = {sp.ccode(reduced[idx])};")
            idx += 1
    for i in range(3):
        lines.append(f"    d.Cdq({i}) = {sp.ccode(reduced[idx])};")
        idx += 1
    for i in range(3):
        lines.append(f"    d.gv({i}) = {sp.ccode(reduced[idx])};")
        idx += 1

    lines += ["    return d;", "}", "", "} // namespace robot_generated", ""]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"[generate] Written: {out_path}", flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Export 3-DOF arm dynamics to C++ header')
    parser.add_argument('--output', default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'generated', 'dynamics_generated.hpp'))
    args = parser.parse_args()

    M, C, g, Q, DQ, L2s, L3s, m2s, m3s, gs = derive_dynamics()
    generate_header(M, C, g, Q, DQ, L2s, L3s, m2s, m3s, gs, args.output)
    print("[done]", flush=True)
