#pragma once
#include <Eigen/Dense>
#include <cmath>
#include "sim_config.hpp"
#include "dynamics_generated.hpp"  // auto-generated by derive_and_export.py

namespace robot {

class RobotArm {
public:
    explicit RobotArm(ArmParams p) : p_(p) {}

    // Full dynamics: returns M, C*dq, g
    robot_generated::DynTerms dynamics(const Eigen::Vector3d& q,
                                        const Eigen::Vector3d& dq) const {
        return robot_generated::compute_dynamics(
            q[0], q[1], q[2], dq[0], dq[1], dq[2],
            p_.L2, p_.L3, p_.m2, p_.m3, p_.grav);
    }

    // Joint acceleration: M^{-1} (tau - Cdq - gv)
    Eigen::Vector3d forward_dynamics(const Eigen::Vector3d& q,
                                     const Eigen::Vector3d& dq,
                                     const Eigen::Vector3d& tau) const {
        auto d = dynamics(q, dq);
        return d.M.llt().solve(tau - d.Cdq - d.gv);
    }

    // Elbow position (world frame)
    Eigen::Vector3d fk_elbow(const Eigen::Vector3d& q) const {
        const double c1 = std::cos(q[0]), s1 = std::sin(q[0]);
        const double c2 = std::cos(q[1]), s2 = std::sin(q[1]);
        return p_.L2 * Eigen::Vector3d{c1 * c2, s1 * c2, -s2};
    }

    // Hand (end-effector) position (world frame)
    Eigen::Vector3d fk_hand(const Eigen::Vector3d& q) const {
        const double c1  = std::cos(q[0]), s1 = std::sin(q[0]);
        const double c23 = std::cos(q[1] + q[2]), s23 = std::sin(q[1] + q[2]);
        return fk_elbow(q) + p_.L3 * Eigen::Vector3d{c1 * c23, s1 * c23, -s23};
    }

    const ArmParams& params() const { return p_; }

private:
    ArmParams p_;
};

} // namespace robot
